experiment_name: test-job
seed: 42

hydra:
  job:
    chdir: True
  run:
    dir: logs/.hydra





# for each positive sample samples 5 negative samples
sampling_negative_ratio: 5


val_size: 0.2
batch_size: 3
num_workers: 2

model:
  name: bert-base-uncased
  max_length: 512
  lr: 2e-5
  weight_decay: 0.01





train:
  max_epochs: 2
  accelerator: cpu
  limit_train_batches: 2
  limit_val_batches: 2



data:
  collie:
    articles: data/cleaned/COLLIE/articles.json
    queries: data/cleaned/COLLIE/query_article.json
    n_queries: 885
  vietnam:
    article: data/cleaned/Vietnam/articles.json
    queries: data/cleaned/Vietnam/query_article.json
